//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ammper64.com.facturainteligenteintegraciones {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService1", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback TimbrarTxtOperationCompleted;
        
        private System.Threading.SendOrPostCallback SellarOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerPorReferenciaOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelarCFDIOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerPorUUIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerComprobantesPeriodoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerPDFOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::ammper64.Properties.Settings.Default.ammper64_com_facturainteligenteintegraciones_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event TimbrarTxtCompletedEventHandler TimbrarTxtCompleted;
        
        /// <remarks/>
        public event SellarCompletedEventHandler SellarCompleted;
        
        /// <remarks/>
        public event ObtenerPorReferenciaCompletedEventHandler ObtenerPorReferenciaCompleted;
        
        /// <remarks/>
        public event CancelarCFDICompletedEventHandler CancelarCFDICompleted;
        
        /// <remarks/>
        public event ObtenerPorUUIDCompletedEventHandler ObtenerPorUUIDCompleted;
        
        /// <remarks/>
        public event ObtenerComprobantesPeriodoCompletedEventHandler ObtenerComprobantesPeriodoCompleted;
        
        /// <remarks/>
        public event ObtenerPDFCompletedEventHandler ObtenerPDFCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/TimbrarTxt", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Respuesta TimbrarTxt([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Peticion _PeticionCliente) {
            object[] results = this.Invoke("TimbrarTxt", new object[] {
                        _PeticionCliente});
            return ((Respuesta)(results[0]));
        }
        
        /// <remarks/>
        public void TimbrarTxtAsync(Peticion _PeticionCliente) {
            this.TimbrarTxtAsync(_PeticionCliente, null);
        }
        
        /// <remarks/>
        public void TimbrarTxtAsync(Peticion _PeticionCliente, object userState) {
            if ((this.TimbrarTxtOperationCompleted == null)) {
                this.TimbrarTxtOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTimbrarTxtOperationCompleted);
            }
            this.InvokeAsync("TimbrarTxt", new object[] {
                        _PeticionCliente}, this.TimbrarTxtOperationCompleted, userState);
        }
        
        private void OnTimbrarTxtOperationCompleted(object arg) {
            if ((this.TimbrarTxtCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TimbrarTxtCompleted(this, new TimbrarTxtCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/Sellar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Respuesta Sellar([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Peticion _PeticionCliente, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string dAdicionales) {
            object[] results = this.Invoke("Sellar", new object[] {
                        _PeticionCliente,
                        dAdicionales});
            return ((Respuesta)(results[0]));
        }
        
        /// <remarks/>
        public void SellarAsync(Peticion _PeticionCliente, string dAdicionales) {
            this.SellarAsync(_PeticionCliente, dAdicionales, null);
        }
        
        /// <remarks/>
        public void SellarAsync(Peticion _PeticionCliente, string dAdicionales, object userState) {
            if ((this.SellarOperationCompleted == null)) {
                this.SellarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSellarOperationCompleted);
            }
            this.InvokeAsync("Sellar", new object[] {
                        _PeticionCliente,
                        dAdicionales}, this.SellarOperationCompleted, userState);
        }
        
        private void OnSellarOperationCompleted(object arg) {
            if ((this.SellarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SellarCompleted(this, new SellarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ObtenerPorReferencia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Respuesta ObtenerPorReferencia([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string usuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string referencia, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ref string error) {
            object[] results = this.Invoke("ObtenerPorReferencia", new object[] {
                        usuario,
                        password,
                        referencia,
                        error});
            error = ((string)(results[1]));
            return ((Respuesta)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerPorReferenciaAsync(string usuario, string password, string referencia, string error) {
            this.ObtenerPorReferenciaAsync(usuario, password, referencia, error, null);
        }
        
        /// <remarks/>
        public void ObtenerPorReferenciaAsync(string usuario, string password, string referencia, string error, object userState) {
            if ((this.ObtenerPorReferenciaOperationCompleted == null)) {
                this.ObtenerPorReferenciaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerPorReferenciaOperationCompleted);
            }
            this.InvokeAsync("ObtenerPorReferencia", new object[] {
                        usuario,
                        password,
                        referencia,
                        error}, this.ObtenerPorReferenciaOperationCompleted, userState);
        }
        
        private void OnObtenerPorReferenciaOperationCompleted(object arg) {
            if ((this.ObtenerPorReferenciaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerPorReferenciaCompleted(this, new ObtenerPorReferenciaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/CancelarCFDI", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RespuestaCancelacion CancelarCFDI([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string usuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string contrasena, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string rfcEmisor, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string uuid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string certificadoPKCS12, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string passwordPKCS12) {
            object[] results = this.Invoke("CancelarCFDI", new object[] {
                        usuario,
                        contrasena,
                        rfcEmisor,
                        uuid,
                        certificadoPKCS12,
                        passwordPKCS12});
            return ((RespuestaCancelacion)(results[0]));
        }
        
        /// <remarks/>
        public void CancelarCFDIAsync(string usuario, string contrasena, string rfcEmisor, string uuid, string certificadoPKCS12, string passwordPKCS12) {
            this.CancelarCFDIAsync(usuario, contrasena, rfcEmisor, uuid, certificadoPKCS12, passwordPKCS12, null);
        }
        
        /// <remarks/>
        public void CancelarCFDIAsync(string usuario, string contrasena, string rfcEmisor, string uuid, string certificadoPKCS12, string passwordPKCS12, object userState) {
            if ((this.CancelarCFDIOperationCompleted == null)) {
                this.CancelarCFDIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelarCFDIOperationCompleted);
            }
            this.InvokeAsync("CancelarCFDI", new object[] {
                        usuario,
                        contrasena,
                        rfcEmisor,
                        uuid,
                        certificadoPKCS12,
                        passwordPKCS12}, this.CancelarCFDIOperationCompleted, userState);
        }
        
        private void OnCancelarCFDIOperationCompleted(object arg) {
            if ((this.CancelarCFDICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelarCFDICompleted(this, new CancelarCFDICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ObtenerPorUUID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Respuesta ObtenerPorUUID([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string usuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string uuid, TipoPDF TipoPDF, [System.Xml.Serialization.XmlIgnoreAttribute()] bool TipoPDFSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string tipoAddenda, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string cadenaAddenda) {
            object[] results = this.Invoke("ObtenerPorUUID", new object[] {
                        usuario,
                        password,
                        uuid,
                        TipoPDF,
                        TipoPDFSpecified,
                        tipoAddenda,
                        cadenaAddenda});
            return ((Respuesta)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerPorUUIDAsync(string usuario, string password, string uuid, TipoPDF TipoPDF, bool TipoPDFSpecified, string tipoAddenda, string cadenaAddenda) {
            this.ObtenerPorUUIDAsync(usuario, password, uuid, TipoPDF, TipoPDFSpecified, tipoAddenda, cadenaAddenda, null);
        }
        
        /// <remarks/>
        public void ObtenerPorUUIDAsync(string usuario, string password, string uuid, TipoPDF TipoPDF, bool TipoPDFSpecified, string tipoAddenda, string cadenaAddenda, object userState) {
            if ((this.ObtenerPorUUIDOperationCompleted == null)) {
                this.ObtenerPorUUIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerPorUUIDOperationCompleted);
            }
            this.InvokeAsync("ObtenerPorUUID", new object[] {
                        usuario,
                        password,
                        uuid,
                        TipoPDF,
                        TipoPDFSpecified,
                        tipoAddenda,
                        cadenaAddenda}, this.ObtenerPorUUIDOperationCompleted, userState);
        }
        
        private void OnObtenerPorUUIDOperationCompleted(object arg) {
            if ((this.ObtenerPorUUIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerPorUUIDCompleted(this, new ObtenerPorUUIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ObtenerComprobantesPeriodo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RespuestaLista ObtenerComprobantesPeriodo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string usuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string rfcEmisor, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string rfcReceptor, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string fecha) {
            object[] results = this.Invoke("ObtenerComprobantesPeriodo", new object[] {
                        usuario,
                        password,
                        rfcEmisor,
                        rfcReceptor,
                        fecha});
            return ((RespuestaLista)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerComprobantesPeriodoAsync(string usuario, string password, string rfcEmisor, string rfcReceptor, string fecha) {
            this.ObtenerComprobantesPeriodoAsync(usuario, password, rfcEmisor, rfcReceptor, fecha, null);
        }
        
        /// <remarks/>
        public void ObtenerComprobantesPeriodoAsync(string usuario, string password, string rfcEmisor, string rfcReceptor, string fecha, object userState) {
            if ((this.ObtenerComprobantesPeriodoOperationCompleted == null)) {
                this.ObtenerComprobantesPeriodoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerComprobantesPeriodoOperationCompleted);
            }
            this.InvokeAsync("ObtenerComprobantesPeriodo", new object[] {
                        usuario,
                        password,
                        rfcEmisor,
                        rfcReceptor,
                        fecha}, this.ObtenerComprobantesPeriodoOperationCompleted, userState);
        }
        
        private void OnObtenerComprobantesPeriodoOperationCompleted(object arg) {
            if ((this.ObtenerComprobantesPeriodoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerComprobantesPeriodoCompleted(this, new ObtenerComprobantesPeriodoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ObtenerPDF", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] ObtenerPDF([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string user, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xmlTimbrado, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string adicionales, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string datosG, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string rfcEmisor, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string uuid, TipoPDF TipoPDF, [System.Xml.Serialization.XmlIgnoreAttribute()] bool TipoPDFSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ref string error) {
            object[] results = this.Invoke("ObtenerPDF", new object[] {
                        user,
                        password,
                        xmlTimbrado,
                        adicionales,
                        datosG,
                        rfcEmisor,
                        uuid,
                        TipoPDF,
                        TipoPDFSpecified,
                        error});
            error = ((string)(results[1]));
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerPDFAsync(string user, string password, string xmlTimbrado, string adicionales, string datosG, string rfcEmisor, string uuid, TipoPDF TipoPDF, bool TipoPDFSpecified, string error) {
            this.ObtenerPDFAsync(user, password, xmlTimbrado, adicionales, datosG, rfcEmisor, uuid, TipoPDF, TipoPDFSpecified, error, null);
        }
        
        /// <remarks/>
        public void ObtenerPDFAsync(string user, string password, string xmlTimbrado, string adicionales, string datosG, string rfcEmisor, string uuid, TipoPDF TipoPDF, bool TipoPDFSpecified, string error, object userState) {
            if ((this.ObtenerPDFOperationCompleted == null)) {
                this.ObtenerPDFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerPDFOperationCompleted);
            }
            this.InvokeAsync("ObtenerPDF", new object[] {
                        user,
                        password,
                        xmlTimbrado,
                        adicionales,
                        datosG,
                        rfcEmisor,
                        uuid,
                        TipoPDF,
                        TipoPDFSpecified,
                        error}, this.ObtenerPDFOperationCompleted, userState);
        }
        
        private void OnObtenerPDFOperationCompleted(object arg) {
            if ((this.ObtenerPDFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerPDFCompleted(this, new ObtenerPDFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfAmmper")]
    public partial class Peticion {
        
        private TipoPDF tipoPDFField;
        
        private bool tipoPDFFieldSpecified;
        
        private string cadenaAddendaField;
        
        private string cadenaComplementoField;
        
        private string cadenaTXTField;
        
        private string contrasenaField;
        
        private string datosGField;
        
        private bool pdfField;
        
        private bool pdfFieldSpecified;
        
        private bool productivoField;
        
        private bool productivoFieldSpecified;
        
        private string rfcEmisorField;
        
        private string tipoAddendaField;
        
        private int tipoCFDIField;
        
        private bool tipoCFDIFieldSpecified;
        
        private string usuarioField;
        
        /// <remarks/>
        public TipoPDF TipoPDF {
            get {
                return this.tipoPDFField;
            }
            set {
                this.tipoPDFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TipoPDFSpecified {
            get {
                return this.tipoPDFFieldSpecified;
            }
            set {
                this.tipoPDFFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cadenaAddenda {
            get {
                return this.cadenaAddendaField;
            }
            set {
                this.cadenaAddendaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cadenaComplemento {
            get {
                return this.cadenaComplementoField;
            }
            set {
                this.cadenaComplementoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cadenaTXT {
            get {
                return this.cadenaTXTField;
            }
            set {
                this.cadenaTXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                this.contrasenaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string datosG {
            get {
                return this.datosGField;
            }
            set {
                this.datosGField = value;
            }
        }
        
        /// <remarks/>
        public bool pdf {
            get {
                return this.pdfField;
            }
            set {
                this.pdfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pdfSpecified {
            get {
                return this.pdfFieldSpecified;
            }
            set {
                this.pdfFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool productivo {
            get {
                return this.productivoField;
            }
            set {
                this.productivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool productivoSpecified {
            get {
                return this.productivoFieldSpecified;
            }
            set {
                this.productivoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string rfcEmisor {
            get {
                return this.rfcEmisorField;
            }
            set {
                this.rfcEmisorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tipoAddenda {
            get {
                return this.tipoAddendaField;
            }
            set {
                this.tipoAddendaField = value;
            }
        }
        
        /// <remarks/>
        public int tipoCFDI {
            get {
                return this.tipoCFDIField;
            }
            set {
                this.tipoCFDIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoCFDISpecified {
            get {
                return this.tipoCFDIFieldSpecified;
            }
            set {
                this.tipoCFDIFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfAmmper")]
    public enum TipoPDF {
        
        /// <remarks/>
        GENERICO_CENACE,
        
        /// <remarks/>
        GENERICO,
        
        /// <remarks/>
        Recibo,
        
        /// <remarks/>
        GENERICO_CENACE_NOTAS,
        
        /// <remarks/>
        GENERICO_PAGOS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfAmmper")]
    public partial class RespuestaLista {
        
        private string[] comprobantesField;
        
        private string errorField;
        
        private bool exitoField;
        
        private bool exitoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] comprobantes {
            get {
                return this.comprobantesField;
            }
            set {
                this.comprobantesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        public bool exito {
            get {
                return this.exitoField;
            }
            set {
                this.exitoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool exitoSpecified {
            get {
                return this.exitoFieldSpecified;
            }
            set {
                this.exitoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfAmmper")]
    public partial class RespuestaCancelacion {
        
        private string acuseCancelacionField;
        
        private bool exitoField;
        
        private bool exitoFieldSpecified;
        
        private string mensaje_errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string acuseCancelacion {
            get {
                return this.acuseCancelacionField;
            }
            set {
                this.acuseCancelacionField = value;
            }
        }
        
        /// <remarks/>
        public bool exito {
            get {
                return this.exitoField;
            }
            set {
                this.exitoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool exitoSpecified {
            get {
                return this.exitoFieldSpecified;
            }
            set {
                this.exitoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mensaje_error {
            get {
                return this.mensaje_errorField;
            }
            set {
                this.mensaje_errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfAmmper")]
    public partial class Respuesta {
        
        private string codigoConfirmacionField;
        
        private string errorEspecificoField;
        
        private string errorGeneralField;
        
        private bool exitoField;
        
        private bool exitoFieldSpecified;
        
        private byte[] pdfField;
        
        private string uuidField;
        
        private string xmlTimbradoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string codigoConfirmacion {
            get {
                return this.codigoConfirmacionField;
            }
            set {
                this.codigoConfirmacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string errorEspecifico {
            get {
                return this.errorEspecificoField;
            }
            set {
                this.errorEspecificoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string errorGeneral {
            get {
                return this.errorGeneralField;
            }
            set {
                this.errorGeneralField = value;
            }
        }
        
        /// <remarks/>
        public bool exito {
            get {
                return this.exitoField;
            }
            set {
                this.exitoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool exitoSpecified {
            get {
                return this.exitoFieldSpecified;
            }
            set {
                this.exitoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] pdf {
            get {
                return this.pdfField;
            }
            set {
                this.pdfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string xmlTimbrado {
            get {
                return this.xmlTimbradoField;
            }
            set {
                this.xmlTimbradoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void TimbrarTxtCompletedEventHandler(object sender, TimbrarTxtCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TimbrarTxtCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TimbrarTxtCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Respuesta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Respuesta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SellarCompletedEventHandler(object sender, SellarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SellarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SellarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Respuesta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Respuesta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ObtenerPorReferenciaCompletedEventHandler(object sender, ObtenerPorReferenciaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerPorReferenciaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerPorReferenciaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Respuesta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Respuesta)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string error {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CancelarCFDICompletedEventHandler(object sender, CancelarCFDICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelarCFDICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelarCFDICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RespuestaCancelacion Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RespuestaCancelacion)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ObtenerPorUUIDCompletedEventHandler(object sender, ObtenerPorUUIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerPorUUIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerPorUUIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Respuesta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Respuesta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ObtenerComprobantesPeriodoCompletedEventHandler(object sender, ObtenerComprobantesPeriodoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerComprobantesPeriodoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerComprobantesPeriodoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RespuestaLista Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RespuestaLista)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ObtenerPDFCompletedEventHandler(object sender, ObtenerPDFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerPDFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerPDFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string error {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591