//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ammper64.s_wspci {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="s_wspci.wspciSoap")]
    public interface wspciSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ammper64.s_wspci.HelloWorldResponse HelloWorld(ammper64.s_wspci.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ammper64.s_wspci.HelloWorldResponse> HelloWorldAsync(ammper64.s_wspci.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getEstadoDeCuenta", ReplyAction="*")]
        ammper64.s_wspci.getEstadoDeCuentaResponse getEstadoDeCuenta(ammper64.s_wspci.getEstadoDeCuentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getEstadoDeCuenta", ReplyAction="*")]
        System.Threading.Tasks.Task<ammper64.s_wspci.getEstadoDeCuentaResponse> getEstadoDeCuentaAsync(ammper64.s_wspci.getEstadoDeCuentaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getExtract", ReplyAction="*")]
        ammper64.s_wspci.getExtractResponse getExtract(ammper64.s_wspci.getExtractRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getExtract", ReplyAction="*")]
        System.Threading.Tasks.Task<ammper64.s_wspci.getExtractResponse> getExtractAsync(ammper64.s_wspci.getExtractRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ammper64.s_wspci.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ammper64.s_wspci.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ammper64.s_wspci.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ammper64.s_wspci.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getEstadoDeCuentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getEstadoDeCuenta", Namespace="http://tempuri.org/", Order=0)]
        public ammper64.s_wspci.getEstadoDeCuentaRequestBody Body;
        
        public getEstadoDeCuentaRequest() {
        }
        
        public getEstadoDeCuentaRequest(ammper64.s_wspci.getEstadoDeCuentaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getEstadoDeCuentaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contrasenia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Interconexion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Subcuenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Date;
        
        public getEstadoDeCuentaRequestBody() {
        }
        
        public getEstadoDeCuentaRequestBody(string usuario, string contrasenia, string Interconexion, string Subcuenta, string Date) {
            this.usuario = usuario;
            this.contrasenia = contrasenia;
            this.Interconexion = Interconexion;
            this.Subcuenta = Subcuenta;
            this.Date = Date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getEstadoDeCuentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getEstadoDeCuentaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ammper64.s_wspci.getEstadoDeCuentaResponseBody Body;
        
        public getEstadoDeCuentaResponse() {
        }
        
        public getEstadoDeCuentaResponse(ammper64.s_wspci.getEstadoDeCuentaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getEstadoDeCuentaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getEstadoDeCuentaResult;
        
        public getEstadoDeCuentaResponseBody() {
        }
        
        public getEstadoDeCuentaResponseBody(string getEstadoDeCuentaResult) {
            this.getEstadoDeCuentaResult = getEstadoDeCuentaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getExtractRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getExtract", Namespace="http://tempuri.org/", Order=0)]
        public ammper64.s_wspci.getExtractRequestBody Body;
        
        public getExtractRequest() {
        }
        
        public getExtractRequest(ammper64.s_wspci.getExtractRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getExtractRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contrasenia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string beginDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string endDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string subcuenta;
        
        public getExtractRequestBody() {
        }
        
        public getExtractRequestBody(string usuario, string contrasenia, string beginDate, string endDate, string subcuenta) {
            this.usuario = usuario;
            this.contrasenia = contrasenia;
            this.beginDate = beginDate;
            this.endDate = endDate;
            this.subcuenta = subcuenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getExtractResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getExtractResponse", Namespace="http://tempuri.org/", Order=0)]
        public ammper64.s_wspci.getExtractResponseBody Body;
        
        public getExtractResponse() {
        }
        
        public getExtractResponse(ammper64.s_wspci.getExtractResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getExtractResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getExtractResult;
        
        public getExtractResponseBody() {
        }
        
        public getExtractResponseBody(string getExtractResult) {
            this.getExtractResult = getExtractResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wspciSoapChannel : ammper64.s_wspci.wspciSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wspciSoapClient : System.ServiceModel.ClientBase<ammper64.s_wspci.wspciSoap>, ammper64.s_wspci.wspciSoap {
        
        public wspciSoapClient() {
        }
        
        public wspciSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wspciSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wspciSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wspciSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ammper64.s_wspci.HelloWorldResponse ammper64.s_wspci.wspciSoap.HelloWorld(ammper64.s_wspci.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ammper64.s_wspci.HelloWorldRequest inValue = new ammper64.s_wspci.HelloWorldRequest();
            inValue.Body = new ammper64.s_wspci.HelloWorldRequestBody();
            ammper64.s_wspci.HelloWorldResponse retVal = ((ammper64.s_wspci.wspciSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ammper64.s_wspci.HelloWorldResponse> ammper64.s_wspci.wspciSoap.HelloWorldAsync(ammper64.s_wspci.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ammper64.s_wspci.HelloWorldResponse> HelloWorldAsync() {
            ammper64.s_wspci.HelloWorldRequest inValue = new ammper64.s_wspci.HelloWorldRequest();
            inValue.Body = new ammper64.s_wspci.HelloWorldRequestBody();
            return ((ammper64.s_wspci.wspciSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ammper64.s_wspci.getEstadoDeCuentaResponse ammper64.s_wspci.wspciSoap.getEstadoDeCuenta(ammper64.s_wspci.getEstadoDeCuentaRequest request) {
            return base.Channel.getEstadoDeCuenta(request);
        }
        
        public string getEstadoDeCuenta(string usuario, string contrasenia, string Interconexion, string Subcuenta, string Date) {
            ammper64.s_wspci.getEstadoDeCuentaRequest inValue = new ammper64.s_wspci.getEstadoDeCuentaRequest();
            inValue.Body = new ammper64.s_wspci.getEstadoDeCuentaRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contrasenia = contrasenia;
            inValue.Body.Interconexion = Interconexion;
            inValue.Body.Subcuenta = Subcuenta;
            inValue.Body.Date = Date;
            ammper64.s_wspci.getEstadoDeCuentaResponse retVal = ((ammper64.s_wspci.wspciSoap)(this)).getEstadoDeCuenta(inValue);
            return retVal.Body.getEstadoDeCuentaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ammper64.s_wspci.getEstadoDeCuentaResponse> ammper64.s_wspci.wspciSoap.getEstadoDeCuentaAsync(ammper64.s_wspci.getEstadoDeCuentaRequest request) {
            return base.Channel.getEstadoDeCuentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ammper64.s_wspci.getEstadoDeCuentaResponse> getEstadoDeCuentaAsync(string usuario, string contrasenia, string Interconexion, string Subcuenta, string Date) {
            ammper64.s_wspci.getEstadoDeCuentaRequest inValue = new ammper64.s_wspci.getEstadoDeCuentaRequest();
            inValue.Body = new ammper64.s_wspci.getEstadoDeCuentaRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contrasenia = contrasenia;
            inValue.Body.Interconexion = Interconexion;
            inValue.Body.Subcuenta = Subcuenta;
            inValue.Body.Date = Date;
            return ((ammper64.s_wspci.wspciSoap)(this)).getEstadoDeCuentaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ammper64.s_wspci.getExtractResponse ammper64.s_wspci.wspciSoap.getExtract(ammper64.s_wspci.getExtractRequest request) {
            return base.Channel.getExtract(request);
        }
        
        public string getExtract(string usuario, string contrasenia, string beginDate, string endDate, string subcuenta) {
            ammper64.s_wspci.getExtractRequest inValue = new ammper64.s_wspci.getExtractRequest();
            inValue.Body = new ammper64.s_wspci.getExtractRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contrasenia = contrasenia;
            inValue.Body.beginDate = beginDate;
            inValue.Body.endDate = endDate;
            inValue.Body.subcuenta = subcuenta;
            ammper64.s_wspci.getExtractResponse retVal = ((ammper64.s_wspci.wspciSoap)(this)).getExtract(inValue);
            return retVal.Body.getExtractResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ammper64.s_wspci.getExtractResponse> ammper64.s_wspci.wspciSoap.getExtractAsync(ammper64.s_wspci.getExtractRequest request) {
            return base.Channel.getExtractAsync(request);
        }
        
        public System.Threading.Tasks.Task<ammper64.s_wspci.getExtractResponse> getExtractAsync(string usuario, string contrasenia, string beginDate, string endDate, string subcuenta) {
            ammper64.s_wspci.getExtractRequest inValue = new ammper64.s_wspci.getExtractRequest();
            inValue.Body = new ammper64.s_wspci.getExtractRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contrasenia = contrasenia;
            inValue.Body.beginDate = beginDate;
            inValue.Body.endDate = endDate;
            inValue.Body.subcuenta = subcuenta;
            return ((ammper64.s_wspci.wspciSoap)(this)).getExtractAsync(inValue);
        }
    }
}
